# 项目级配置
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX 配置
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin 代码风格
kotlin.code.style=official

# 强制 Non-transitive R 类以加速构建
android.nonTransitiveAppRClass=true
